# Generated by Django 5.2.11 on 2026-02-28 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0003_alter_train_cargo_num_alter_train_places_in_cargo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["id"]},
        ),
    ]
