# Generated by Django 5.2.11 on 2026-03-01 04:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0004_alter_ticket_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="cargo",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="seat",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="train",
            name="cargo_num",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="train",
            name="places_in_cargo",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
